path: /data/ocr/idcard_detection/idcard_segment  # dataset root dir
train: train
val: val

names:
  0: kr-idcard                # 주민등록증
  1: kr-driver                # 운전면허증
  2: passport                 # 여권
  3: kr-alien-resident        # 외국인등록증
  4: kr-permanent-resident    # 영주증
  5: kr-overseas-resident     # 거소증
  6: vn-cccd-nochip-front
  7: vn-cccd-nochip-back
  8: vn-cccd-chip-front
  9: vn-cccd-chip-back
  10: vn-cmnd-front
  11: vn-cmnd-back
  12: vn-driver-chip-front
  13: vn-driver-chip-back
  14: vn-passport